/*
 * Revenue Management System
 *
 * Florida Fish and Wildlife Conservation Commision - Revenue Management System.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: apiteam@fwc.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Collections.Generic;
using Microsoft.AspNetCore.Mvc;
using Swashbuckle.AspNetCore.Annotations;
using Swashbuckle.AspNetCore.SwaggerGen;
using Newtonsoft.Json;
using System.ComponentModel.DataAnnotations;
using FWC.RMS.Attributes;
using FWC.RMS.Security;
using Microsoft.AspNetCore.Authorization;
using FWC.RMS.ApplicationCore.DTOs;
using FWC.RMS.ApplicationCore.Interfaces;

namespace FWC.RMS.Controllers
{ 
    /// <summary>
    /// 
    /// </summary>
    [ApiController]
    public class DepartmentDocumentSearchApiController : ControllerBase
    {

        private readonly IDepartmentDocumentSearchService _departmentDocumentSearchService;

        /// <summary>
        /// 
        /// </summary>
        /// <param name="departmentDocumentSearchService"></param>
        public DepartmentDocumentSearchApiController(IDepartmentDocumentSearchService departmentDocumentSearchService)
        {
            _departmentDocumentSearchService = departmentDocumentSearchService;
        }


        /// <summary>
        /// Search Department Document records
        /// </summary>
        /// <param name="body">Department Document search request</param>
        /// <response code="200">successful operation</response>
        /// <response code="400">Bad request</response>
        /// <response code="500">Internal server error</response>
        [HttpPost]
        [Route("/v1/departmentDocumentSearch")]
        [ValidateModelState]
        [SwaggerOperation("SearchDepartmentDocuments")]
        [SwaggerResponse(statusCode: 200, type: typeof(List<DepartmentDocumentSearchResponse>), description: "successful operation")]
        public virtual IActionResult SearchDepartmentDocuments([FromBody]DepartmentDocumentSearchRequest body)
        {
            try
            {
                return new ObjectResult(_departmentDocumentSearchService.AdvancedSearch(body));
            }
            catch (Exception) 
            { 
                return StatusCode(500); 
            }
        }

        /// <summary>
        /// Search Department Document records by keyword
        /// </summary>
        /// <param name="keyword">Search Keyword (FirstName or LastName)</param>
        /// <response code="200">successful operation</response>
        /// <response code="400">Bad request</response>
        /// <response code="500">Internal server error</response>
        [HttpGet]
        [Route("/v1/departmentDocumentSearch")]
        [ValidateModelState]
        [SwaggerOperation("SearchDepartmentDocumentsByKeyword")]
        [SwaggerResponse(statusCode: 200, type: typeof(List<DepartmentDocumentSearchResponse>), description: "successful operation")]
        public virtual IActionResult SearchDepartmentDocumentsByKeyword([FromQuery][Required()]string keyword)
        {
            try
            {
                return new ObjectResult(_departmentDocumentSearchService.BasicSearch(keyword));
            }
            catch (Exception) 
            { 
                return StatusCode(500); 
            }
        }
    }
}
